// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Sociala_Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sociala_Entities.Concrete.DatabaseFirst
{
    public partial class Comment : IEntity
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]

        public int Id { get; set; }
        public string CommentMessage { get; set; }
        public string CommentDate { get; set; }
        public int PostIdForComment { get; set; }
        public int UserIdForComment { get; set; }

        public virtual Post PostIdForCommentNavigation { get; set; }
        public virtual User UserIdForCommentNavigation { get; set; }
    }
}