// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sociala_Entities.Concrete.DatabaseFirst
{
    public partial class currentchatResult
    {
        public string MessageText { get; set; }
        public string MessageDate { get; set; }
        public int SenderUserId { get; set; }
        public int ReceiverUserId { get; set; }
    }
}
