// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Sociala_Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sociala_Entities.Concrete.DatabaseFirst
{
    public partial class NotificationReceiver : IEntity
    {
        public NotificationReceiver()
        {
            Notification = new HashSet<Notification>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string NotificationMessage { get; set; }
        public string NotificationDate { get; set; }
        public int UserIdForNotificationLineAsReceiver { get; set; }

        public virtual User UserIdForNotificationLineAsReceiverNavigation { get; set; }
        public virtual ICollection<Notification> Notification { get; set; }
    }
}