// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Http;
using Sociala_Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sociala_Entities.Concrete.DatabaseFirst
{
    public partial class Post : IEntity
    {
        public Post()
        {
            Comment = new HashSet<Comment>();
            PostandTag = new HashSet<PostandTag>();
            Reaction = new HashSet<Reaction>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string PostMessage { get; set; }
        public string PostImage { get; set; }
        public string PostVideo { get; set; }
        public string PostDate { get; set; }
        public int UserIdForPost { get; set; }

        public virtual User UserIdForPostNavigation { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<PostandTag> PostandTag { get; set; }
        public virtual ICollection<Reaction> Reaction { get; set; }


        [NotMapped]
        //[DisplayName("Upload images")]
        //[FileSize(5555555, 555555)] // min: 0.5298185348510742 MB; max: 5.298190116882324 MB
        //[AllowedExtensions(new string[] { ".png", ".jpeg" })]
        //[DataType(DataType.Upload)]
        public IFormFile imagePath { get; set; }

        [NotMapped]
        //[DisplayName("Upload videos")]
        //[FileSize(555555555, 555555)] // min: 0.5298185348510742 MB; max: 529.8190641403198 MB
        //[AllowedExtensions(new string[] { ".mp4", ".mov" })]
        //[DataType(DataType.Upload)]
        public IFormFile videoPath { get; set; }
    }
}