// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Sociala_Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sociala_Entities.Concrete.DatabaseFirst
{
    public partial class PostandTag : IEntity
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int? PostIdForPostandTag { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int? TagIdForPostandTag { get; set; }

        public virtual Post PostIdForPostandTagNavigation { get; set; }
        public virtual Tag TagIdForPostandTagNavigation { get; set; }
    }
}