// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Sociala_Entities.Concrete.DatabaseFirst;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Sociala_Entities.Concrete.DatabaseFirst
{
    public partial class SocialadbContext
    {
        private SocialadbContextProcedures _procedures;

        public virtual SocialadbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new SocialadbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public SocialadbContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<currentchatResult>().HasNoKey().ToView(null);
        }
    }

    public interface ISocialadbContextProcedures
    {
        Task<List<currentchatResult>> currentchatAsync(long? receiveruserId, long? senderuserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }

    public partial class SocialadbContextProcedures : ISocialadbContextProcedures
    {
        private readonly SocialadbContext _context;

        public SocialadbContextProcedures(SocialadbContext context)
        {
            _context = context;
        }

        public virtual async Task<List<currentchatResult>> currentchatAsync(long? receiveruserId, long? senderuserId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "receiveruserId",
                    Value = receiveruserId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                new SqlParameter
                {
                    ParameterName = "senderuserId",
                    Value = senderuserId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.BigInt,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<currentchatResult>("EXEC @returnValue = [dbo].[currentchat] @receiveruserId, @senderuserId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
