// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Sociala_Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sociala_Entities.Concrete.DatabaseFirst
{
    public partial class Tag : IEntity
    {
        public Tag()
        {
            PostandTag = new HashSet<PostandTag>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string TagTitle1 { get; set; }
        public string TagTitle2 { get; set; }
        public string TagTitle3 { get; set; }
        public string TagTitle4 { get; set; }
        public string TagTitle5 { get; set; }
        public string TagTitle6 { get; set; }
        public string TagTitle7 { get; set; }
        public string TagTitle8 { get; set; }
        public string TagTitle9 { get; set; }
        public string TagTitle10 { get; set; }
        public string TagTitle11 { get; set; }
        public string TagTitle12 { get; set; }

        public virtual ICollection<PostandTag> PostandTag { get; set; }
    }
}