// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Sociala_Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sociala_Entities.Concrete.DatabaseFirst
{
    public partial class User : IEntity
    {
        public User()
        {
            Comment = new HashSet<Comment>();
            Friend = new HashSet<Friend>();
            MessageReceiverUser = new HashSet<Message>();
            MessageSenderUser = new HashSet<Message>();
            NotificationReceiver = new HashSet<NotificationReceiver>();
            NotificationSender = new HashSet<NotificationSender>();
            Post = new HashSet<Post>();
            Reaction = new HashSet<Reaction>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string UserOnlineDate { get; set; }
        public string Username { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string UserFilepath { get; set; }

        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Friend> Friend { get; set; }
        public virtual ICollection<Message> MessageReceiverUser { get; set; }
        public virtual ICollection<Message> MessageSenderUser { get; set; }
        public virtual ICollection<NotificationReceiver> NotificationReceiver { get; set; }
        public virtual ICollection<NotificationSender> NotificationSender { get; set; }
        public virtual ICollection<Post> Post { get; set; }
        public virtual ICollection<Reaction> Reaction { get; set; }
    }
}